package codegen

import (
	"fmt"
	"sort"
	"strings"
)

// Declarations renders a `.d.ts`-style block for the given namespaces. This is
// what `mcpx types` prints and what an agent pastes into its context: only the
// namespaces it asked for, nothing else.
func Declarations(nss []Namespace) string {
	var b strings.Builder
	b.WriteString("// Generated by mcpx. Call these from a script run with `mcpx run <file.ts>`.\n")
	b.WriteString("// Every function is async and returns the tool's result.\n\n")

	sort.Slice(nss, func(i, j int) bool { return nss[i].Name < nss[j].Name })
	for _, ns := range nss {
		b.WriteString(namespaceDoc(ns))
		fmt.Fprintf(&b, "declare namespace %s {\n", ns.Name)
		tools := append([]Tool(nil), ns.Tools...)
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })
		for i, t := range tools {
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString(toolDecl(t, "  "))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// namespaceDoc renders the namespace description and the server's own
// instructions. The instructions are the only place conventions like "call
// list_pages first to get a pageId" are stated, so they belong next to the
// signatures rather than being discarded.
func namespaceDoc(ns Namespace) string {
	desc := strings.TrimSpace(ns.Description)
	prelude := strings.TrimSpace(ns.Prelude)
	instr := strings.TrimSpace(ns.Instructions)
	if desc == "" && prelude == "" && instr == "" {
		return ""
	}
	if prelude == "" && instr == "" {
		return "/** " + sanitizeComment(desc) + " */\n"
	}
	var b strings.Builder
	b.WriteString("/**\n")
	if desc != "" {
		b.WriteString(" * " + sanitizeComment(desc) + "\n *\n")
	}
	// The operator's prelude comes first: it is the more specific statement,
	// written by someone who knows what this deployment gets wrong.
	if prelude != "" {
		writeCommentBlock(&b, "Notes:", prelude)
	}
	if instr != "" {
		if prelude != "" {
			b.WriteString(" *\n")
		}
		writeCommentBlock(&b, "Server guidance:", instr)
	}
	b.WriteString(" */\n")
	return b.String()
}

func writeCommentBlock(b *strings.Builder, title, body string) {
	b.WriteString(" * " + title + "\n")
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimRight(line, " \t\r")
		if line == "" {
			b.WriteString(" *\n")
			continue
		}
		b.WriteString(" * " + sanitizeComment(line) + "\n")
	}
}

func toolDecl(t Tool, indent string) string {
	var b strings.Builder
	if d := strings.TrimSpace(t.Description); d != "" {
		lines := strings.Split(d, "\n")
		b.WriteString(indent + "/**\n")
		for _, l := range lines {
			b.WriteString(indent + " * " + sanitizeComment(l) + "\n")
		}
		b.WriteString(indent + " */\n")
	}
	argsType, optional := ArgsTypeFor(t.InputSchema, indent)
	opt := ""
	if optional {
		opt = "?"
	}
	fn := ToolFuncName(t.Name)
	fmt.Fprintf(&b, "%sfunction %s(args%s: %s): Promise<ToolResult>;\n", indent, fn, opt, argsType)
	return b.String()
}

// Module renders the importable client module. Scripts do:
//
//	import { fff, chrome_devtools } from "./.mcpx/client.ts";
//
// or use the default `tools` object. The module is written to disk, so the
// JavaScript runtime's own module cache applies and startup stays at tens of
// milliseconds.
func Module(nss []Namespace, endpoint, session string) string {
	var b strings.Builder
	b.WriteString(moduleHeader)
	fmt.Fprintf(&b, "const DEFAULT_ENDPOINT = %s;\n", quote(endpoint))
	fmt.Fprintf(&b, "const DEFAULT_SESSION = %s;\n\n", quote(session))
	b.WriteString(moduleRuntime)

	sort.Slice(nss, func(i, j int) bool { return nss[i].Name < nss[j].Name })

	for _, ns := range nss {
		tools := append([]Tool(nil), ns.Tools...)
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

		b.WriteString(namespaceDoc(ns))
		fmt.Fprintf(&b, "export const %s = {\n", ns.Name)
		for i, t := range tools {
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString(toolImpl(ns.Server, t, "  "))
		}
		b.WriteString("};\n\n")
	}

	b.WriteString("export const tools = {\n")
	for _, ns := range nss {
		fmt.Fprintf(&b, "  %s,\n", ns.Name)
	}
	b.WriteString("};\n\nexport default tools;\n")
	return b.String()
}

func toolImpl(server string, t Tool, indent string) string {
	var b strings.Builder
	if d := strings.TrimSpace(t.Description); d != "" {
		lines := strings.Split(d, "\n")
		b.WriteString(indent + "/**\n")
		for _, l := range lines {
			b.WriteString(indent + " * " + sanitizeComment(l) + "\n")
		}
		b.WriteString(indent + " */\n")
	}
	argsType, optional := ArgsTypeFor(t.InputSchema, indent)
	opt := ""
	if optional {
		opt = "?"
	}
	fn := ToolFuncName(t.Name)
	fmt.Fprintf(&b, "%s%s(args%s: %s): Promise<ToolResult> {\n", indent, fn, opt, argsType)
	fmt.Fprintf(&b, "%s  return __call(%s, %s, args);\n", indent, quote(server), quote(t.Name))
	fmt.Fprintf(&b, "%s},\n", indent)
	return b.String()
}

const moduleHeader = `// Generated by mcpx. Do not edit; regenerated whenever tool schemas change.
//
// Each function posts one tools/call to the local mcpx daemon, which owns the
// MCP server processes. Results are returned already unwrapped: a text-only
// result becomes a string, a structured result becomes the parsed object.
// Reach for .raw on the returned value when you need the full MCP envelope.

`

const moduleRuntime = `function env(name: string): string {
  // Works on Deno, Bun and Node without assuming any of them.
  try {
    const d = (globalThis as any).Deno;
    if (d?.env?.get) return d.env.get(name) ?? "";
  } catch { /* permission denied: fall through */ }
  try {
    const p = (globalThis as any).process;
    if (p?.env) return p.env[name] ?? "";
  } catch { /* not Node-like */ }
  return "";
}

// The session and endpoint are read at run time rather than baked in, so that
// concurrent runs sharing one generated client file still get their own
// session. That isolation is what gives each run its own browser in
// session-mode pools.
const ENDPOINT = env("MCPX_ENDPOINT") || DEFAULT_ENDPOINT;
const SESSION = env("MCPX_SESSION") || DEFAULT_SESSION;

/** A filesystem location, as given and as fully resolved. */
export interface PathPair {
  /** The path as mcpx was given it, symlinks and all. */
  readonly path: string;
  /** The same location with every symlink resolved. */
  readonly real: string;
}

function realpath(p: string): string {
  if (!p) return p;
  try {
    const d = (globalThis as any).Deno;
    if (d?.realPathSync) return d.realPathSync(p);
  } catch { /* not Deno, or denied */ }
  try {
    // Bun and Node both expose node:fs; require is available in Bun/CJS and
    // createRequire covers the rest without a static import.
    const req = (globalThis as any).require ??
      (globalThis as any).process?.getBuiltinModule?.bind((globalThis as any).process);
    const fs = req ? req("node:fs") : undefined;
    if (fs?.realpathSync) return fs.realpathSync(p);
  } catch { /* fall through */ }
  return p;
}

function pair(p: string): PathPair {
  return { path: p, real: realpath(p) };
}

function fromFileUrl(url: string): string {
  if (!url.startsWith("file://")) return url;
  const withoutScheme = decodeURIComponent(url.slice("file://".length));
  // file:///abs on unix; strip a leading host component if one is present.
  return withoutScheme.startsWith("/") ? withoutScheme : "/" + withoutScheme.replace(/^[^/]*\//, "");
}

/**
 * Where things are, from the point of view of any file in the import graph.
 *
 * These come from the environment rather than from module scope, so a script
 * three imports deep sees the same cwd and entry as the file the user
 * actually named. Use here(import.meta) for the current file.
 */
export const paths = {
  /** The directory the user ran mcpx from. */
  cwd: pair(env("MCPX_CWD")),
  /** The script mcpx was asked to run. Empty for mcpx exec. */
  entry: pair(env("MCPX_ENTRY")),
  /** This generated client module. */
  client: pair(env("MCPX_CLIENT")),
  /** The config file in effect, if any. */
  config: pair(env("MCPX_CONFIG_PATH")),
  /** Directories searched for named scripts, nearest first. */
  scriptDirs: (env("MCPX_SCRIPT_DIRS") || "").split(":").filter(Boolean),
};

/**
 * The file this is called from.
 *
 *     import { here } from "./mcpx-client.ts";
 *     const self = here(import.meta);   // { path, real }
 *
 * A module-level constant cannot do this: it would resolve once, in the
 * client, and every importer would see the client's own path.
 */
export function here(meta: { url: string }): PathPair {
  return pair(fromFileUrl(meta.url));
}

/** The directory containing the file this is called from. */
export function hereDir(meta: { url: string }): PathPair {
  const p = fromFileUrl(meta.url);
  const dir = p.slice(0, Math.max(0, p.lastIndexOf("/"))) || "/";
  return pair(dir);
}

export interface ContentBlock {
  type: string;
  text?: string;
  data?: string;
  mimeType?: string;
  uri?: string;
  [key: string]: unknown;
}

export interface RawToolResult {
  content?: ContentBlock[];
  structuredContent?: unknown;
  isError?: boolean;
  [key: string]: unknown;
}

/**
 * The value a tool call resolves to.
 *
 * It behaves as the useful part of the result (parsed structured content, or
 * the concatenated text) while still carrying the full envelope on .raw.
 */
export type ToolResult = any;

export class ToolError extends Error {
  // Written as plain fields rather than constructor parameter properties:
  // Node's type-stripping mode erases types without transforming code, and
  // parameter properties need a transform. Plain fields run everywhere.
  server: string;
  tool: string;
  raw?: unknown;

  constructor(message: string, server: string, tool: string, raw?: unknown) {
    super(message);
    this.name = "ToolError";
    this.server = server;
    this.tool = tool;
    this.raw = raw;
  }
}

function attachRaw<T>(value: T, raw: RawToolResult): T {
  if (value !== null && typeof value === "object") {
    try {
      Object.defineProperty(value, "raw", { value: raw, enumerable: false, configurable: true });
    } catch { /* frozen object: leave it alone */ }
    return value;
  }
  // Primitives cannot carry properties; box strings so .raw still works.
  if (typeof value === "string") {
    const boxed = new String(value) as unknown as T;
    Object.defineProperty(boxed, "raw", { value: raw, enumerable: false, configurable: true });
    return boxed;
  }
  return value;
}

function unwrap(server: string, tool: string, raw: RawToolResult): ToolResult {
  if (raw && raw.isError) {
    const text = (raw.content ?? [])
      .filter((c) => c.type === "text" && typeof c.text === "string")
      .map((c) => c.text)
      .join("\n");
    throw new ToolError(text || ` + "`" + `${server}.${tool} returned isError` + "`" + `, server, tool, raw);
  }
  if (raw && raw.structuredContent !== undefined) {
    return attachRaw(raw.structuredContent as ToolResult, raw);
  }
  const blocks = raw?.content ?? [];
  const texts = blocks.filter((c) => c.type === "text" && typeof c.text === "string");
  if (texts.length === blocks.length && texts.length > 0) {
    const joined = texts.map((c) => c.text as string).join("\n");
    // Servers commonly return JSON as text; hand back the parsed value when
    // it parses cleanly, since that is almost always what the script wants.
    const t = joined.trim();
    if ((t.startsWith("{") && t.endsWith("}")) || (t.startsWith("[") && t.endsWith("]"))) {
      try {
        return attachRaw(JSON.parse(t) as ToolResult, raw);
      } catch { /* not JSON after all */ }
    }
    return attachRaw(joined as ToolResult, raw);
  }
  return attachRaw(blocks as ToolResult, raw);
}

async function __call(server: string, tool: string, args: unknown): Promise<ToolResult> {
  let resp: Response;
  try {
    resp = await fetch(ENDPOINT + "/v1/call", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-mcpx-session": SESSION,
        "x-mcpx-call": SESSION,
        "x-mcpx-cwd": env("MCPX_CWD"),
        "x-mcpx-pid": env("MCPX_PID"),
        "x-mcpx-parent-session": env("MCPX_PARENT_SESSION_ID"),
        "x-mcpx-ephemeral": env("MCPX_EPHEMERAL"),
      },
      body: JSON.stringify({ server, tool, args: args ?? {} }),
    });
  } catch (e) {
    throw new ToolError(
      ` + "`" + `cannot reach the mcpx daemon at ${ENDPOINT}: ${(e as Error).message}` + "`" + `,
      server,
      tool,
    );
  }
  const body = await resp.json().catch(() => ({ error: ` + "`" + `bad response (http ${resp.status})` + "`" + ` }));
  if (!resp.ok || body.error) {
    throw new ToolError(body.error ?? ` + "`" + `http ${resp.status}` + "`" + `, server, tool, body);
  }
  return unwrap(server, tool, body.result as RawToolResult);
}

export type LogLevel = "debug" | "info" | "warn" | "error";

/** Structured values attached to a log record. */
export type LogAttrs = Record<string, unknown>;

const LOG_SENTINEL = "\u001emcpx\u001e";

const LEVEL_ORDER: Record<LogLevel, number> = { debug: 0, info: 1, warn: 2, error: 3 };

function levelFrom(name: string, fallback: number): number {
  const n = LEVEL_ORDER[name.trim().toLowerCase() as LogLevel];
  return n === undefined ? fallback : n;
}

// The active threshold, so a filtered call costs a comparison instead of a
// JSON encode and a write. The runner passes the same value it will filter on,
// which keeps the two ends from disagreeing.
const MIN_LEVEL = levelFrom(env("MCPX_LOG_LEVEL"), LEVEL_ORDER.info);

/**
 * Levels whose records carry a call site.
 *
 * Capture costs about 5 microseconds -- building the stack, not reading it --
 * which is roughly fifty times the cost of the record itself. Paying that on
 * every info line is waste; paying it on a warning is the moment you most want
 * to know where it came from. So the default traces warn and above, and
 * MCPX_LOG_SOURCE widens it to everything.
 */
const SOURCE_LEVELS: number = env("MCPX_LOG_SOURCE") === "1"
  ? LEVEL_ORDER.debug
  : env("MCPX_LOG_SOURCE") === "0"
  ? Number.POSITIVE_INFINITY
  : levelFrom(env("MCPX_LOG_SOURCE"), LEVEL_ORDER.warn);

function writeStderr(line: string): void {
  const d = (globalThis as any).Deno;
  if (d?.stderr?.writeSync) {
    d.stderr.writeSync(new TextEncoder().encode(line + "\n"));
    return;
  }
  const p = (globalThis as any).process;
  if (p?.stderr?.write) {
    p.stderr.write(line + "\n");
    return;
  }
  console.error(line);
}

/** A plain data object, as opposed to an Error, an array or a primitive. */
function isAttrs(v: unknown): v is LogAttrs {
  return typeof v === "object" && v !== null && !Array.isArray(v) &&
    !(v instanceof Error) && Object.getPrototypeOf(v) === Object.prototype;
}

function describeError(e: Error): LogAttrs {
  return { name: e.name, message: e.message, ...(e.stack ? { stack: e.stack } : {}) };
}

/**
 * Where the call came from, read out of a synthetic stack trace.
 *
 * Only called when the level warrants it, because constructing the Error is
 * the expensive half.
 */
function callSite(): LogAttrs | undefined {
  const stack = new Error().stack;
  if (!stack) return undefined;
  const lines = stack.split("\n").slice(1);
  const frame = lines.find((l) => !l.includes("mcpx-client"));
  if (!frame) return undefined;
  const m = frame.match(/at\s+(?:(.+?)\s+\()?(?:file:\/\/)?([^()]+?):(\d+):(\d+)\)?\s*$/);
  if (!m) return undefined;
  const [, fn, file, line, col] = m;
  return {
    "source.file": file,
    "source.line": Number(line),
    "source.column": Number(col),
    ...(fn ? { "source.function": fn } : {}),
  };
}

function send(kind: "log" | "result", payload: Record<string, unknown>): void {
  writeStderr(LOG_SENTINEL + JSON.stringify({ kind, ts: new Date().toISOString(), ...payload }));
}

function emitRecord(level: LogLevel, bound: LogAttrs, msg: string, rest: unknown[]): void {
  // Short-circuit before any work. A debug call in a loop should cost a
  // comparison when nothing will print.
  const n = LEVEL_ORDER[level];
  if (n < MIN_LEVEL) return;

  let attrs: LogAttrs = { ...bound };
  const extra: unknown[] = [];
  for (const [i, v] of rest.entries()) {
    if (i === 0 && isAttrs(v)) {
      Object.assign(attrs, v);
      continue;
    }
    extra.push(v instanceof Error ? describeError(v) : v);
  }
  if (extra.length > 0) attrs.args = extra;
  if (n >= SOURCE_LEVELS) Object.assign(attrs, callSite());

  const hasTemplate = msg.includes("{");
  send("log", {
    level,
    msg,
    ...(hasTemplate ? { template: msg } : {}),
    ...(Object.keys(attrs).length > 0 ? { attrs } : {}),
  });
}

/** A logger, optionally carrying attributes bound by with(). */
export interface Logger {
  debug(msg: string, ...rest: unknown[]): void;
  info(msg: string, ...rest: unknown[]): void;
  warn(msg: string, ...rest: unknown[]): void;
  error(msg: string, ...rest: unknown[]): void;
  /**
   * A logger carrying these attributes on every record, mirroring slog's
   * Logger.With.
   *
   * The returned logger must be passed where it is needed; JavaScript has no
   * ambient context, so bindings do not follow the call stack on their own.
   *
   *     const scoped = log.with({ run: runId });
   *     await scan(scoped, file);
   */
  with(attrs: LogAttrs): Logger;
  /** True when a record at this level would be emitted. */
  enabled(level: LogLevel): boolean;
}

function makeLogger(bound: LogAttrs): Logger {
  return {
    debug: (msg, ...rest) => emitRecord("debug", bound, msg, rest),
    info: (msg, ...rest) => emitRecord("info", bound, msg, rest),
    warn: (msg, ...rest) => emitRecord("warn", bound, msg, rest),
    error: (msg, ...rest) => emitRecord("error", bound, msg, rest),
    with: (attrs: LogAttrs) => makeLogger({ ...bound, ...attrs }),
    enabled: (level: LogLevel) => LEVEL_ORDER[level] >= MIN_LEVEL,
  };
}

/**
 * Structured logging for scripts.
 *
 * A message may carry {placeholders} filled from the attributes, and {{x}}
 * writes a literal {x}:
 *
 *     log.info("fetched {count} pages in {ms}ms", { count: 3, ms: 412 });
 *
 * The first argument after the message is treated as attributes when it is a
 * plain object. Anything else, and anything after it, is collected into an
 * "args" array, so console-style calls still carry their values rather than
 * being dropped:
 *
 *     log.error("upload failed", err);            // err becomes args[0]
 *     log.debug("state", { id }, "extra", 42);    // id is an attribute
 *
 * Both the rendered message and its template are kept, so output reads as
 * prose and still groups by shape. stdout stays clear for results; this is
 * stderr.
 */
export const log: Logger = makeLogger({});

/**
 * Stream a result before the script finishes.
 *
 * A script's return value is one answer delivered at the end. emit() is for
 * many answers delivered as they are found: a long crawl, a per-file report, a
 * progress feed a caller can act on without waiting.
 *
 *     for (const file of files) emit({ file, findings: await scan(file) });
 *
 * Each value is written immediately. In ordinary use it lands on stdout as one
 * JSON line per call; under mcpx --json run the values are collected into
 * the envelope's results array in order. Either way the consumer sees them
 * in sequence rather than as one blob at the end.
 */
export function emitResult(value: unknown): void {
  send("result", { value });
}

export { emitResult as emit };

/** Call any tool by name, including ones added after this client was generated. */
export async function call(server: string, tool: string, args?: unknown): Promise<ToolResult> {
  return __call(server, tool, args ?? {});
}

/** Read an MCP resource URI. */
export async function readResource(server: string, uri: string): Promise<ToolResult> {
  const resp = await fetch(ENDPOINT + "/v1/resource", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-mcpx-session": SESSION,
      "x-mcpx-call": SESSION,
      "x-mcpx-cwd": env("MCPX_CWD"),
      "x-mcpx-pid": env("MCPX_PID"),
      "x-mcpx-parent-session": env("MCPX_PARENT_SESSION_ID"),
    },
    body: JSON.stringify({ server, uri }),
  });
  const body = await resp.json();
  if (!resp.ok || body.error) throw new ToolError(body.error ?? ` + "`" + `http ${resp.status}` + "`" + `, server, uri);
  return body.result;
}

`
