_: {
  homebrew.casks = [
    "1password"
    "1password-cli"
    "alt-tab"
    "amethyst"
    # "angry-ip-scanner" # DEPRECATED — find replacement
    "appcleaner"
    "asana"
    "audacity"
    "audio-hijack"
    "balenaetcher"
    "bartender"
    "cmux" # nixpkgs PR pending: https://github.com/NixOS/nixpkgs/pull/493537
    "contexts"
    "cursor"
    "discord"
    "displaylink"
    "drawio"
    "element"
    "firefox"
    "font-hack-nerd-font"
    "font-inconsolata-g-for-powerline"
    "font-source-code-pro-for-powerline"
    # "ghostty" # switched to nixpkgs ghostty-bin (pre-built binary managed by home-manager)
    # "gitkraken"
    # "gitkraken-cli"
    "github@beta"
    "google-chrome"
    "hammerspoon"
    "handbrake"
    "homebrew/cask/docker"
    "imageoptim"
    "insomnia"
    "iterm2@nightly"
    "keepingyouawake"
    "keycastr"
    # "libreoffice"
    "logseq"
    "loom"
    "macfuse" # required for bindfs (opencode-share)
    # "makemkv"
    # "meld"
    "microsoft-edge"
    "microsoft-excel"
    "microsoft-onenote"
    "microsoft-outlook"
    "microsoft-powerpoint"
    "microsoft-teams"
    "microsoft-word"
    "mkvtoolnix" # replaces deprecated mkvtoolnix-app
    # "nextcloud"
    # "ngrok"
    "notion"
    "onedrive"
    "onyx" # system maintenance, cache cleaning, Spotlight reindexing
    # "onlyoffice"
    "postico"
    "raycast"
    "rectangle"
    "safari-technology-preview"
    "signal"
    "slack"
    "snagit"
    # "sonos"
    # "steam"
    # "superkey"
    "syncthing"
    "tableplus"
    # "tailscale"
    "telegram"
    "usb-overdrive"
    # "vivaldi"
    "visual-studio-code"
    "visual-studio-code@insiders"
    "vlc"
    "webex"
    "windows-app"
    "wireshark"
    "zed"
    "zen-browser"
    "zoom"
  ];
}
