code --install-extension vscode.bat --force
code --install-extension vscode.builtin-notebook-renderers --force
code --install-extension vscode.clojure --force
code --install-extension vscode.coffeescript --force
code --install-extension vscode.configuration-editing --force
code --install-extension vscode.cpp --force
code --install-extension vscode.csharp --force
code --install-extension vscode.css --force
code --install-extension vscode.css-language-features --force
code --install-extension vscode.dart --force
code --install-extension vscode.debug-auto-launch --force
code --install-extension vscode.debug-server-ready --force
code --install-extension vscode.diff --force
code --install-extension vscode.docker --force
code --install-extension vscode.emmet --force
code --install-extension vscode.extension-editing --force
code --install-extension vscode.fsharp --force
code --install-extension vscode.git --force
code --install-extension vscode.git-base --force
code --install-extension vscode.github --force
code --install-extension vscode.github-authentication --force
code --install-extension vscode.go --force
code --install-extension vscode.groovy --force
code --install-extension vscode.grunt --force
code --install-extension vscode.gulp --force
code --install-extension vscode.handlebars --force
code --install-extension vscode.hlsl --force
code --install-extension vscode.html --force
code --install-extension vscode.html-language-features --force
code --install-extension vscode.image-preview --force
code --install-extension vscode.ini --force
code --install-extension vscode.ipynb --force
code --install-extension vscode.jake --force
code --install-extension vscode.java --force
code --install-extension vscode.javascript --force
code --install-extension vscode.json --force
code --install-extension vscode.json-language-features --force
code --install-extension vscode.julia --force
code --install-extension vscode.latex --force
code --install-extension vscode.less --force
code --install-extension vscode.log --force
code --install-extension vscode.lua --force
code --install-extension vscode.make --force
code --install-extension vscode.markdown --force
code --install-extension vscode.markdown-language-features --force
code --install-extension vscode.markdown-math --force
code --install-extension vscode.media-preview --force
code --install-extension vscode.merge-conflict --force
code --install-extension vscode.microsoft-authentication --force
code --install-extension vscode.npm --force
code --install-extension vscode.objective-c --force
code --install-extension vscode.perl --force
code --install-extension vscode.php --force
code --install-extension vscode.php-language-features --force
code --install-extension vscode.powershell --force
code --install-extension vscode.pug --force
code --install-extension vscode.python --force
code --install-extension vscode.r --force
code --install-extension vscode.razor --force
code --install-extension vscode.references-view --force
code --install-extension vscode.restructuredtext --force
code --install-extension vscode.ruby --force
code --install-extension vscode.rust --force
code --install-extension vscode.scss --force
code --install-extension vscode.search-result --force
code --install-extension vscode.shaderlab --force
code --install-extension vscode.shellscript --force
code --install-extension vscode.simple-browser --force
code --install-extension vscode.sql --force
code --install-extension vscode.swift --force
code --install-extension vscode.theme-abyss --force
code --install-extension vscode.theme-defaults --force
code --install-extension vscode.theme-kimbie-dark --force
code --install-extension vscode.theme-monokai --force
code --install-extension vscode.theme-monokai-dimmed --force
code --install-extension vscode.theme-quietlight --force
code --install-extension vscode.theme-red --force
code --install-extension vscode.theme-solarized-dark --force
code --install-extension vscode.theme-solarized-light --force
code --install-extension vscode.theme-tomorrow-night-blue --force
code --install-extension vscode.tunnel-forwarding --force
code --install-extension vscode.typescript --force
code --install-extension vscode.typescript-language-features --force
code --install-extension vscode.vb --force
code --install-extension vscode.vscode-theme-seti --force
code --install-extension vscode.xml --force
code --install-extension vscode.yaml --force
code --install-extension 4ops.packer --force
code --install-extension 4ops.terraform --force
code --install-extension a5huynh.vscode-ron --force
code --install-extension aaron-bond.better-comments --force
code --install-extension aaronthomas.vscode-snazzy-operator --force
code --install-extension abhinavk99.codewall --force
code --install-extension abierbaum.vscode-file-peek --force
code --install-extension adamcaviness.theme-monokai-dark-soda --force
code --install-extension adrianwilczynski.add-reference --force
code --install-extension adrianwilczynski.asp-net-core-snippet-pack --force
code --install-extension adrianwilczynski.asp-net-core-switcher --force
code --install-extension adrianwilczynski.blazor-snippet-pack --force
code --install-extension adrianwilczynski.csharp-to-typescript --force
code --install-extension adrianwilczynski.libman --force
code --install-extension adrianwilczynski.namespace --force
code --install-extension adrianwilczynski.terminal-commands --force
code --install-extension adrianwilczynski.toggle-hidden --force
code --install-extension adrianwilczynski.user-secrets --force
code --install-extension agurodriguez.vscode-lbnf --force
code --install-extension ahmadalli.vscode-nginx-conf --force
code --install-extension ahmadawais.shades-of-purple --force
code --install-extension ajshortt.tokyo-hack --force
code --install-extension alber70g.solarized-light-differentiated --force
code --install-extension aldijav.golangwithdidi --force
code --install-extension alefragnani.bookmarks --force
code --install-extension alefragnani.project-manager --force
code --install-extension alexanderbast.vscode-snazzy --force
code --install-extension alexnho.a-touch-of-lilac-theme --force
code --install-extension aliasadidev.nugetpackagemanagergui --force
code --install-extension almenon.arepl --force
code --install-extension altbdoor.change-tab-size --force
code --install-extension altcoda.cybervision --force
code --install-extension amazonwebservices.aws-toolkit-vscode --force
code --install-extension amirha.better-comments-2 --force
code --install-extension andrewvallette.zeonica --force
code --install-extension andyyaldoo.vscode-json --force
code --install-extension annalifatou.minimal-wave --force
code --install-extension anseki.vscode-color --force
code --install-extension anweber.vscode-httpyac --force
code --install-extension aramok.aramoks-black --force
code --install-extension arcticicestudio.nord-visual-studio-code --force
code --install-extension arjunumathanu.monokai-dark-pro --force
code --install-extension arrterian.nix-env-selector --force
code --install-extension arthurdiegoo.great-dreamer --force
code --install-extension arturock.gitstash --force
code --install-extension artymaury.template-finder --force
code --install-extension asf.apache-netbeans-java --force
code --install-extension asilverio.blackai-visual-studio-code --force
code --install-extension astro-build.astro-vscode --force
code --install-extension atishay-jain.all-autocomplete --force
code --install-extension austenc.tailwind-docs --force
code --install-extension awehook.vscode-blink-mind --force
code --install-extension aws-scripting-guy.cform --force
code --install-extension axiomaticstudios.one-monokai-80s --force
code --install-extension azemoh.one-monokai --force
code --install-extension bajdzis.vscode-database --force
code --install-extension bbenoist.nix --force
code --install-extension bbenoist.vagrant --force
code --install-extension bceskavich.theme-dracula-at-night --force
code --install-extension belfz.search-crates-io --force
code --install-extension benbusby.earthbound-themes --force
code --install-extension bencoleman.armview --force
code --install-extension benjaminmandersen.midnight-pastel --force
code --install-extension betterthantomorrow.calva --force
code --install-extension betterthantomorrow.calva-spritz --force
code --install-extension bibhasdn.unique-lines --force
code --install-extension bierner.color-info --force
code --install-extension bierner.github-markdown-preview --force
code --install-extension bierner.markdown-checkbox --force
code --install-extension bierner.markdown-emoji --force
code --install-extension bierner.markdown-footnotes --force
code --install-extension bierner.markdown-mermaid --force
code --install-extension bierner.markdown-preview-github-styles --force
code --install-extension bierner.markdown-yaml-preamble --force
code --install-extension bitlang.vscode-crosshair --force
code --install-extension blairleduc.net-core-starters-pack --force
code --install-extension bmuskalla.vscode-tldr --force
code --install-extension bradlc.vscode-tailwindcss --force
code --install-extension bram209.leptos-language-server --force
code --install-extension brenix.hacker-theme --force
code --install-extension brettm12345.nixfmt-vscode --force
code --install-extension brunoventura.sqltools-athena-driver --force
code --install-extension buenon.scratchpads --force
code --install-extension caarlos0.language-prometheus --force
code --install-extension cardinal90.multi-cursor-case-preserve --force
code --install-extension cargo-inspect-vscode.cargo-inspect --force
code --install-extension carlos18mz.cyberpunk-2077-rebuild --force
code --install-extension chadbaileyvh.oled-pure-black---vscode --force
code --install-extension chakrounanas.turbo-console-log --force
code --install-extension chiperific.authzed --force
code --install-extension chouzz.vscode-better-align --force
code --install-extension christian-kohler.npm-intellisense --force
code --install-extension christian-kohler.path-intellisense --force
code --install-extension chrmarti.regex --force
code --install-extension ckolkman.vscode-postgres --force
code --install-extension clarkyu.vscode-sql-beautify --force
code --install-extension clerian.cyberdyne20xx --force
code --install-extension codeandstuff.package-json-upgrade --force
code --install-extension codestream.codestream --force
code --install-extension codezombiech.gitignore --force
code --install-extension coenraads.bracket-pair-colorizer-2 --force
code --install-extension compilenix.vscode-zonefile --force
code --install-extension compulim.indent4to2 --force
code --install-extension connorcpu.vsc-rustfmt --force
code --install-extension conradludgate.rust-playground --force
code --install-extension cschlosser.doxdocgen --force
code --install-extension csdotav.synthwave84-monokai-edition --force
code --install-extension ctenbrinke.ansi16 --force
code --install-extension ctf0.macros --force
code --install-extension ctrlplusb.i-minimal-theme --force
code --install-extension ctrlplusb.white-italic --force
code --install-extension cval.pastel-theme --force
code --install-extension cweijan.dbclient-jdbc --force
code --install-extension cweijan.vscode-postgresql-client2 --force
code --install-extension d4nyll.devops-extension-pack --force
code --install-extension danbackes.lines --force
code --install-extension danidandev.comment-remover --force
code --install-extension danielsanmedium.dscodegpt --force
code --install-extension danielthielking.aws-cloudformation-yaml --force
code --install-extension dannysteenman.cloudformation-yaml-snippets --force
code --install-extension dariofuzinato.vue-peek --force
code --install-extension davidanson.vscode-markdownlint --force
code --install-extension davidhouchin.whitespace-plus --force
code --install-extension daylerees.rainglow --force
code --install-extension dbaeumer.vscode-eslint --force
code --install-extension dbankier.vscode-quick-select --force
code --install-extension ddh4r4m.night-hacker-dark-theme --force
code --install-extension dennismaxjung.vscode-dotnet-auto-attach --force
code --install-extension dhedgecock.radical-vscode --force
code --install-extension dillonchanis.midnight-city --force
code --install-extension dlahmad.dracula-for-rust-theme --force
code --install-extension doggy8088.netcore-extension-pack --force
code --install-extension doggy8088.netcore-snippets --force
code --install-extension doggy8088.quicktype-refresh --force
code --install-extension donjayamanne.git-extension-pack --force
code --install-extension donjayamanne.githistory --force
code --install-extension donjayamanne.jquerysnippets --force
code --install-extension donjayamanne.python-environment-manager --force
code --install-extension donjayamanne.python-extension-pack --force
code --install-extension dotcypress.vscode-cargo-test --force
code --install-extension dotjoshjohnson.xml --force
code --install-extension dracula-theme.theme-dracula --force
code --install-extension dsznajder.es7-react-js-snippets --force
code --install-extension dunn.redis --force
code --install-extension dunstontc.vscode-docker-syntax --force
code --install-extension dunstontc.vscode-rust-syntax --force
code --install-extension dustypomerleau.rust-syntax --force
code --install-extension duszekmestre.stacktraceformatter --force
code --install-extension dzannotti.vscode-babel-coloring --force
code --install-extension eamodio.gitlens --force
code --install-extension earshinov.permute-lines --force
code --install-extension ecmel.vscode-html-css --force
code --install-extension editorconfig.editorconfig --force
code --install-extension eliverlara.andromeda --force
code --install-extension emilast.logfilehighlighter --force
code --install-extension emmanuelbeziat.vscode-great-icons --force
code --install-extension endormi.2077-theme --force
code --install-extension enkia.tokyo-night --force
code --install-extension erd0s.terraform-autocomplete --force
code --install-extension erik-rosengren.dark-candy --force
code --install-extension eriklynd.json-tools --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension euskadi31.json-pretty-printer --force
code --install-extension evan-buss.font-switcher --force
code --install-extension evgeniypeshkov.syntax-highlighter --force
code --install-extension evondev.dracula-high-contrast --force
code --install-extension exelord.git-commits --force
code --install-extension explodeo.oled-black --force
code --install-extension ezzak.nighthawk --force
code --install-extension fab1o.dark-plus-with-italics --force
code --install-extension fabianlauer.vs-code-xml-format --force
code --install-extension fabiospampinato.vscode-diff --force
code --install-extension fallenmax.mithril-emmet --force
code --install-extension fehey.brackets-light-pro --force
code --install-extension felipecaputo.git-project-manager --force
code --install-extension felschr.extbundles-csharp --force
code --install-extension file-icons.file-icons --force
code --install-extension filikos.awesome-go-vscode --force
code --install-extension firefox-devtools.vscode-firefox-debug --force
code --install-extension fisheva.eva-theme --force
code --install-extension florianduros.theme-dracula-italics-turbo --force
code --install-extension formulahendry.auto-close-tag --force
code --install-extension formulahendry.auto-complete-tag --force
code --install-extension formulahendry.auto-rename-tag --force
code --install-extension formulahendry.code-runner --force
code --install-extension formulahendry.docker-explorer --force
code --install-extension formulahendry.docker-extension-pack --force
code --install-extension formulahendry.dotnet --force
code --install-extension formulahendry.dotnet-test-explorer --force
code --install-extension formulahendry.github-actions --force
code --install-extension formulahendry.vscode-mysql --force
code --install-extension foxundermoon.shell-format --force
code --install-extension fredwangwang.vscode-hcl-format --force
code --install-extension fwcd.kotlin --force
code --install-extension genieai.chatgpt-vscode --force
code --install-extension gerane.theme-blackboard --force
code --install-extension gerane.theme-dark-dracula --force
code --install-extension gerane.theme-flatlandmonokai --force
code --install-extension gerane.theme-neon --force
code --install-extension gerane.theme-pastelsondark --force
code --install-extension ghgofort.neon-vommit --force
code --install-extension github.codespaces --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension github.copilot-labs --force
code --install-extension github.github-vscode-theme --force
code --install-extension github.heygithub --force
code --install-extension github.remotehub --force
code --install-extension github.vscode-github-actions --force
code --install-extension github.vscode-pull-request-github --force
code --install-extension golang.go --force
code --install-extension grapecity.gc-excelviewer --force
code --install-extension graphql.vscode-graphql-syntax --force
code --install-extension gruntfuggly.todo-tree --force
code --install-extension gustavoinacio.oled-neon-theme --force
code --install-extension harryhopkinson.vs-code-runner --force
code --install-extension hashicorp.hcl --force
code --install-extension hashicorp.sentinel --force
code --install-extension hashicorp.terraform --force
code --install-extension hbenl.vscode-test-explorer --force
code --install-extension hcltechnologies.hclappscancodesweep --force
code --install-extension hdevalke.rust-test-lens --force
code --install-extension heybourn.headwind --force
code --install-extension hollowtree.vue-snippets --force
code --install-extension hookyqr.minify --force
code --install-extension hoovercj.vscode-settings-cycler --force
code --install-extension hsnazar.hyper-term-theme --force
code --install-extension huizhou.githd --force
code --install-extension humao.rest-client --force
code --install-extension idbartosz.darkpp-italic --force
code --install-extension idleberg.hopscotch --force
code --install-extension idleberg.icon-fonts --force
code --install-extension igochkov.vscode-ebnf --force
code --install-extension iket0731.symbol-navigate-back --force
code --install-extension iliazeus.vscode-ansi --force
code --install-extension infracost.infracost --force
code --install-extension inksea.inksea-theme --force
code --install-extension inu1255.easy-snippet --force
code --install-extension ionide.ionide-fsharp --force
code --install-extension ionutvmi.path-autocomplete --force
code --install-extension ipedrazas.kubernetes-snippets --force
code --install-extension ivory-lab.jenkinsfile-support --force
code --install-extension j0hnm4r5.laser-theme --force
code --install-extension jaakko.black --force
code --install-extension jabacchetta.vscode-essentials --force
code --install-extension jack89ita.open-file-from-path --force
code --install-extension jakearl.search-editor-apply-changes --force
code --install-extension jakethashi.vscode-angular2-emmet --force
code --install-extension janne252.fontawesome-autocomplete --force
code --install-extension jasonlhy.hungry-delete --force
code --install-extension jasonnutter.search-node-modules --force
code --install-extension jbelford.cyberpunk-plus --force
code --install-extension jedeop.crates-completer --force
code --install-extension jeff-hykin.better-cpp-syntax --force
code --install-extension jeff-hykin.better-dockerfile-syntax --force
code --install-extension jeff-hykin.code-eol --force
code --install-extension jfrog.jfrog-vscode-extension --force
code --install-extension jkjustjoshing.vscode-text-pastry --force
code --install-extension jmrog.vscode-nuget-package-manager --force
code --install-extension jnoortheen.nix-ide --force
code --install-extension joaomoreno.github-sharp-theme --force
code --install-extension johnpapa.vscode-peacock --force
code --install-extension josephcz.vscode-markdown-mindmap-preview --force
code --install-extension josetr.cmake-language-support-vscode --force
code --install-extension jprestidge.theme-material-theme --force
code --install-extension jrieken.fuzzy-definitions --force
code --install-extension jrobsonchase.rust-extension-pack --force
code --install-extension jscearcy.rust-doc-viewer --force
code --install-extension jsjlewis96.one-dark-pro-italic-vivid --force
code --install-extension justin-grote.powershell-extension-pack --force
code --install-extension k--kato.docomment --force
code --install-extension k--kato.intellij-idea-keybindings --force
code --install-extension karigari.chat --force
code --install-extension kddejong.vscode-cfn-lint --force
code --install-extension kdl-org.kdl --force
code --install-extension kdl.kdshade --force
code --install-extension kdlanguage.vscode-kd --force
code --install-extension kelvin.vscode-sshfs --force
code --install-extension kevinkassimo.cargo-toml-snippets --force
code --install-extension kevinkyang.auto-comment-blocks --force
code --install-extension kevinrose.vsc-python-indent --force
code --install-extension kisstkondoros.vscode-codemetrics --force
code --install-extension kiteco.kite --force
code --install-extension kreativ-software.csharpextensions --force
code --install-extension l13rary.l13-diff --force
code --install-extension lacroixdavid1.vscode-format-context-menu --force
code --install-extension launchdarklyofficial.launchdarkly --force
code --install-extension leelupyuen.visual-embedded-rust --force
code --install-extension leizongmin.node-module-intellisense --force
code --install-extension letmaik.git-tree-compare --force
code --install-extension lfurzewaddock.vscode-wsl-workspacefolder --force
code --install-extension littlefoxteam.vscode-python-test-adapter --force
code --install-extension liviuschera.noctis --force
code --install-extension loganarnett.lambda-snippets --force
code --install-extension lorenzopirro.rust-flash-snippets --force
code --install-extension lostintangent.vsls-whiteboard --force
code --install-extension louiswt.regexp-preview --force
code --install-extension lrecknagel.one-monokai-italic --force
code --install-extension mads-hartmann.bash-ide-vscode --force
code --install-extension magicstack.magicpython --force
code --install-extension magson.dark-hacker-theme --force
code --install-extension maracko.json-to-go --force
code --install-extension marcostazi.vs-code-vagrantfile --force
code --install-extension mark-tucker.aws-cli-configure --force
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus --force
code --install-extension markis.code-coverage --force
code --install-extension marlon407.code-groovy --force
code --install-extension martellaj.license-injector --force
code --install-extension marus25.cortex-debug --force
code --install-extension matheusq94.tfs --force
code --install-extension mathiasfrohlich.kotlin --force
code --install-extension matthewpi.caddyfile-support --force
code --install-extension maurobussini.vscode-dotnet-essentials --force
code --install-extension maziac.asm-code-lens --force
code --install-extension mblode.one-dark-italic --force
code --install-extension mblode.pretty-formatter --force
code --install-extension mcu-debug.debug-tracker-vscode --force
code --install-extension mcu-debug.memory-view --force
code --install-extension mcu-debug.peripheral-viewer --force
code --install-extension mcu-debug.rtos-views --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension medo64.render-crlf --force
code --install-extension meezilla.json --force
code --install-extension metaseed.metago --force
code --install-extension mgesbert.python-path --force
code --install-extension mgmcdermott.vscode-language-babel --force
code --install-extension mhutchie.git-graph --force
code --install-extension micnil.vscode-checkpoints --force
code --install-extension mikestead.dotenv --force
code --install-extension mindaro-dev.file-downloader --force
code --install-extension mindaro.mindaro --force
code --install-extension miramac.vscode-exec-node --force
code --install-extension mkhl.direnv --force
code --install-extension modular-mojotools.vscode-mojo --force
code --install-extension mohsen1.prettify-json --force
code --install-extension mooman219.rust-assist --force
code --install-extension mosapride.zenkaku --force
code --install-extension moshfeu.compare-folders --force
code --install-extension ms-azure-devops.azure-pipelines --force
code --install-extension ms-azuretools.azure-dev --force
code --install-extension ms-azuretools.vscode-azureappservice --force
code --install-extension ms-azuretools.vscode-azurecontainerapps --force
code --install-extension ms-azuretools.vscode-azurefunctions --force
code --install-extension ms-azuretools.vscode-azureresourcegroups --force
code --install-extension ms-azuretools.vscode-azurestaticwebapps --force
code --install-extension ms-azuretools.vscode-azurestorage --force
code --install-extension ms-azuretools.vscode-azureterraform --force
code --install-extension ms-azuretools.vscode-azurevirtualmachines --force
code --install-extension ms-azuretools.vscode-bicep --force
code --install-extension ms-azuretools.vscode-cosmosdb --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-cst-e.vscode-devskim --force
code --install-extension ms-dotnettools.csdevkit --force
code --install-extension ms-dotnettools.csharp --force
code --install-extension ms-dotnettools.vscode-dotnet-pack --force
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force
code --install-extension ms-dotnettools.vscodeintellicode-csharp --force
code --install-extension ms-edgedevtools.vscode-edge-devtools --force
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --force
code --install-extension ms-mssql.data-workspace-vscode --force
code --install-extension ms-mssql.mssql --force
code --install-extension ms-mssql.sql-bindings-vscode --force
code --install-extension ms-mssql.sql-database-projects-vscode --force
code --install-extension ms-ossdata.vscode-postgresql --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.isort --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode-remote.remote-ssh-edit --force
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension ms-vscode-remote.remote-wsl-recommender --force
code --install-extension ms-vscode-remote.vscode-remote-extensionpack --force
code --install-extension ms-vscode.anycode --force
code --install-extension ms-vscode.anycode-c-sharp --force
code --install-extension ms-vscode.anycode-cpp --force
code --install-extension ms-vscode.anycode-go --force
code --install-extension ms-vscode.anycode-java --force
code --install-extension ms-vscode.anycode-kotlin --force
code --install-extension ms-vscode.anycode-php --force
code --install-extension ms-vscode.anycode-python --force
code --install-extension ms-vscode.anycode-rust --force
code --install-extension ms-vscode.anycode-typescript --force
code --install-extension ms-vscode.azure-account --force
code --install-extension ms-vscode.azure-repos --force
code --install-extension ms-vscode.azurecli --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cpptools-extension-pack --force
code --install-extension ms-vscode.cpptools-themes --force
code --install-extension ms-vscode.hexeditor --force
code --install-extension ms-vscode.js-debug --force
code --install-extension ms-vscode.js-debug-companion --force
code --install-extension ms-vscode.js-debug-nightly --force
code --install-extension ms-vscode.makefile-tools --force
code --install-extension ms-vscode.powershell --force
code --install-extension ms-vscode.references-view --force
code --install-extension ms-vscode.remote-explorer --force
code --install-extension ms-vscode.remote-repositories --force
code --install-extension ms-vscode.remote-server --force
code --install-extension ms-vscode.sublime-keybindings --force
code --install-extension ms-vscode.test-adapter-converter --force
code --install-extension ms-vscode.theme-markdownkit --force
code --install-extension ms-vscode.vscode-js-profile-table --force
code --install-extension ms-vscode.vscode-node-azure-pack --force
code --install-extension ms-vscode.vscode-speech --force
code --install-extension ms-vscode.vscode-typescript-next --force
code --install-extension ms-vscode.wordcount --force
code --install-extension ms-vsliveshare.vsliveshare --force
code --install-extension ms-vsliveshare.vsliveshare-pack --force
code --install-extension msazurermtools.azurerm-vscode-tools --force
code --install-extension msjsdiag.vscode-react-native --force
code --install-extension mtxr.sqltools --force
code --install-extension mtxr.sqltools-driver-mssql --force
code --install-extension mtxr.sqltools-driver-pg --force
code --install-extension mtxr.sqltools-driver-sqlite --force
code --install-extension mushan.vscode-paste-image --force
code --install-extension mziyabo.vscode-codedeploy --force
code --install-extension naco-siren.gradle-language --force
code --install-extension naren.kismat --force
code --install-extension naumovs.color-highlight --force
code --install-extension neonxp.gotools --force
code --install-extension nexxai.material-synthwave-vscode --force
code --install-extension nhoizey.gremlins --force
code --install-extension nixon.env-cmd-file-syntax --force
code --install-extension njpwerner.autodocstring --force
code --install-extension noturnal-theme.dark --force
code --install-extension nur.just-black --force
code --install-extension nuuf.theme-hackershaze --force
code --install-extension nyxiative.rust-and-friends --force
code --install-extension octref.vetur --force
code --install-extension oderwat.indent-rainbow --force
code --install-extension odubuc.mysql-inline-decorator --force
code --install-extension openfga.openfga-vscode --force
code --install-extension oracle-labs-graalvm.graalvm --force
code --install-extension oracle-labs-graalvm.graalvm-pack --force
code --install-extension oracle-labs-graalvm.micronaut --force
code --install-extension orobiti.orobiti --force
code --install-extension orta.vscode-jest --force
code --install-extension outthislife.otl-theme --force
code --install-extension parthr2031.colorful-comments --force
code --install-extension peakchen90.open-html-in-browser --force
code --install-extension peterschmalfeldt.explorer-exclude --force
code --install-extension pflannery.vscode-versionlens --force
code --install-extension philsinatra.popping-and-locking-vscode-black --force
code --install-extension pinage404.nix-extension-pack --force
code --install-extension pivotal.vscode-spring-boot --force
code --install-extension pizycki.pretty-exception --force
code --install-extension pjmiravalle.terraform-advanced-syntax-highlighting --force
code --install-extension pkief.material-icon-theme --force
code --install-extension platformio.platformio-ide --force
code --install-extension pnp.polacode --force
code --install-extension pod212.vscode-github-projects --force
code --install-extension polymeilex.rust-targets --force
code --install-extension polypus74.trusty-rusty-snippets --force
code --install-extension postman.postman-for-vscode --force
code --install-extension pradiphudekar.cf-templates --force
code --install-extension pranaygp.vscode-css-peek --force
code --install-extension premparihar.gotestexplorer --force
code --install-extension pspester.pester-test --force
code --install-extension puppet.puppet-vscode --force
code --install-extension qezhu.gitlink --force
code --install-extension qufiwefefwoyn.inline-sql-syntax --force
code --install-extension quicktype.quicktype --force
code --install-extension qwtel.sqlite-viewer --force
code --install-extension rafamel.subtle-brackets --force
code --install-extension rafistatar.addlocalnetreferences --force
code --install-extension randomchance.logstash --force
code --install-extension rangav.vscode-thunder-client --force
code --install-extension raynigon.nginx-formatter --force
code --install-extension redhat.ansible --force
code --install-extension redhat.fabric8-analytics --force
code --install-extension redhat.java --force
code --install-extension redhat.vscode-xml --force
code --install-extension redhat.vscode-yaml --force
code --install-extension rexebin.f12-open-file --force
code --install-extension richie5um2.vscode-sort-json --force
code --install-extension rioj7.vscode-json-validate --force
code --install-extension ritwickdey.liveserver --force
code --install-extension robbowen.synthwave-vscode --force
code --install-extension rodrigovallades.es7-react-js-snippets --force
code --install-extension rogalmic.bash-debug --force
code --install-extension rpinski.shebang-snippets --force
code --install-extension rubyjasmin.hyperterm-theme --force
code --install-extension run-at-scale.terraform-doc-snippets --force
code --install-extension rust-lang.rust-analyzer --force
code --install-extension ryu1kn.annotator --force
code --install-extension ryu1kn.partial-diff --force
code --install-extension ryuta46.multi-command --force
code --install-extension sanbox.gm-code-vsc --force
code --install-extension sebastienma.ansi-color-code --force
code --install-extension secanis.jenkinsfile-support --force
code --install-extension seven1bit.vscode-ext-ansi-color-highlight --force
code --install-extension shakram02.bash-beautify --force
code --install-extension shardulm94.trailing-spaces --force
code --install-extension shd101wyy.markdown-preview-enhanced --force
code --install-extension siberianmh.rust-grammar --force
code --install-extension sidp.strict-whitespace --force
code --install-extension sirtori.indenticator --force
code --install-extension skyran.js-jsx-snippets --force
code --install-extension sleistner.vscode-fileutils --force
code --install-extension slevesque.vscode-multiclip --force
code --install-extension slevesque.vscode-zipexplorer --force
code --install-extension smartbearsoftware.vscode-swaggerhub --force
code --install-extension smartertomato.locate-this-document --force
code --install-extension sncmn.hide-stream --force
code --install-extension snyk-security.snyk-vulnerability-scanner --force
code --install-extension sohamkamani.code-eol --force
code --install-extension solarliner.linux-themes --force
code --install-extension solomonkinard.git-blame --force
code --install-extension sonarsource.sonarlint-vscode --force
code --install-extension spmeesseman.vscode-taskexplorer --force
code --install-extension spywhere.guides --force
code --install-extension statiolake.vscode-rustfmt --force
code --install-extension steoates.autoimport --force
code --install-extension stkb.rewrap --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension supermaven.supermaven --force
code --install-extension svelte.svelte-vscode --force
code --install-extension svipas.control-snippets --force
code --install-extension swellaby.rust-pack --force
code --install-extension swellaby.vscode-rust-test-adapter --force
code --install-extension sztheory.vscode-packer-powertools --force
code --install-extension tamasfe.even-better-toml --force
code --install-extension taoklerks.poor-mans-t-sql-formatter-vscode --force
code --install-extension techer.open-in-browser --force
code --install-extension theumletteam.umlet --force
code --install-extension thewh1teagle.unexcept --force
code --install-extension threadheap.serverless-ide-vscode --force
code --install-extension thundra.thundra-debugger --force
code --install-extension timonwong.shellcheck --force
code --install-extension tintoy.msbuild-project-tools --force
code --install-extension tobias-faller.vt100-syntax-highlighting --force
code --install-extension tobias-z.vscode-harpoon --force
code --install-extension tobysmith568.run-in-powershell --force
code --install-extension tomoki1207.pdf --force
code --install-extension tonybaloney.vscode-pets --force
code --install-extension trybick.terminal-zoom --force
code --install-extension tsqllint.tsqllint --force
code --install-extension tushortz.python-extended-snippets --force
code --install-extension twxs.cmake --force
code --install-extension tylerleonhardt.vscode-inline-values-powershell --force
code --install-extension tyriar.sort-lines --force
code --install-extension uctakeoff.vscode-counter --force
code --install-extension uiua-lang.uiua-vscode --force
code --install-extension ultram4rine.vscode-choosealicense --force
code --install-extension usernamehw.errorlens --force
code --install-extension usernamehw.remove-empty-lines --force
code --install-extension vadimcn.vscode-lldb --force
code --install-extension vallentin.vscode-bnf --force
code --install-extension vincaslt.highlight-matching-tag --force
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
code --install-extension visualstudioexptteam.vscodeintellicode-completions --force
code --install-extension visualstudioexptteam.vscodeintellicode-insiders --force
code --install-extension vscjava.vscode-gradle --force
code --install-extension vscjava.vscode-java-debug --force
code --install-extension vscjava.vscode-java-dependency --force
code --install-extension vscjava.vscode-java-pack --force
code --install-extension vscjava.vscode-java-test --force
code --install-extension vscjava.vscode-maven --force
code --install-extension vscode-aws-console.vscode-aws-console --force
code --install-extension vscode-icons-team.vscode-icons --force
code --install-extension vscode-org-mode.org-mode --force
code --install-extension vscodevim.vim --force
code --install-extension vsls-contrib.codetour --force
code --install-extension vsls-contrib.gistfs --force
code --install-extension vsls-contrib.gitdoc --force
code --install-extension vue.volar --force
code --install-extension w8eight.oled-dark --force
code --install-extension waderyan.gitblame --force
code --install-extension wallabyjs.quokka-vscode --force
code --install-extension wayou.vscode-todo-highlight --force
code --install-extension wholroyd.jinja --force
code --install-extension william-voyek.vscode-nginx --force
code --install-extension wix.vscode-import-cost --force
code --install-extension wolfulus.rust-extension-pack --force
code --install-extension wowbox.code-debuger --force
code --install-extension wraith13.bracket-lens --force
code --install-extension wraith13.zoombar-vscode --force
code --install-extension wyattferguson.jinja2-snippet-kit --force
code --install-extension xyz.local-history --force
code --install-extension yamachu.targetframeworksswitcher --force
code --install-extension yamajyn.commandlist --force
code --install-extension ybaumes.highlight-trailing-white-spaces --force
code --install-extension ymotongpoo.licenser --force
code --install-extension ypresto.vscode-intelli-refactor --force
code --install-extension ysemeniuk.emmet-live --force
code --install-extension yzhang.markdown-all-in-one --force
code --install-extension zainchen.json --force
code --install-extension zakcodes.rust-snippets --force
code --install-extension zamerick.vscode-caddyfile-syntax --force
code --install-extension zerotaskx.rust-extension-pack --force
code --install-extension zhang-renyang.chat-gpt --force
code --install-extension zhangyue.rust-mod-generator --force
code --install-extension zignd.html-css-class-completion --force
code --install-extension ziyasal.vscode-open-in-github --force
code --install-extension zxh404.vscode-proto3 --force
