package conformance

// Tools, resources, prompts.
func init() {
	// Aggregation is done by the daemon's registry, above the protocol: it is
	// the same whatever revision an upstream speaks, so these tests hold it
	// for 2026-07-28 as for every other.
	register(
		C("tools-aggregator-disambiguate", "e2e.TestDuplicateNamespaceIsRejected@2026-07-28",
			"e2e.TestAliasExposesASubsetOfTheSameServer@2026-07-28"),
		C("tools-aggregator-not-by-servername", "e2e.TestDuplicateNamespaceIsRejected@2026-07-28"),
		SReq("conformance.TestFeaturesServer",
			"tools-declare-capability",
			"resources-declare-capability",
			"prompts-declare-capability",
			"prompts-declare-capability-discover",
			"resources-cap-features-independent",
			"tools-list-must-respond-when-declared",
			"resources-list-must-respond-when-declared",
			"prompts-list-must-respond-when-declared",
			"tools-list-may-be-empty-change",
			"tools-embedded-implies-resources-cap",
			"tools-list-not-per-connection",
			"resources-list-not-per-connection",
			"prompts-list-not-per-connection",
			"tools-list-deterministic-order",
			"tools-list-changed-notify",
			"tools-list-changed-notify-to-listeners",
			"prompts-list-changed-notify",
			"prompts-list-changed-notify-to-listeners",
			"resources-list-changed-notify",
			"tools-list-changed-means-emit",
			"tools-inputschema-type-object-root",
			"tools-inputschema-valid-not-null",
			"tools-inputschema-no-params-recommended",
			"tools-name-length",
			"tools-name-charset",
			"tools-name-no-special",
			"tools-name-unique-in-server",
			"tools-output-schema-conform",
			"tools-output-schema-object-root",
			"tools-structured-also-text",
			"tools-structured-any-json",
			"tools-structured-object-only",
			"tools-error-unknown-tool-protocol",
			"tools-result-lookup-errors-protocol",
			"tools-name-case-sensitive",
			"tools-result-iserror-for-tool-errors",
			"tools-error-input-validation-execution",
			"tools-error-invalid-args-protocol",
			"tools-embedded-resource-may",
			"tools-resource-link-may",
			"tools-resource-link-may-not-listed",
			"tools-call-input-required-may",
			"tools-call-inputrequests-declared-only",
			"resources-read-input-required-may",
			"prompts-get-input-required-may",
			"resources-not-found-32002",
			"resources-not-found-32602",
			"resources-no-empty-contents-for-missing",
			"resources-internal-32603",
			"resources-read-multiple-may",
			"resources-file-xdg-mime-may",
			"resources-https-only-if-client-fetchable",
			"resources-https-else-other-scheme",
			"resources-annotations-defs",
			"resources-sec-validate-uris",
			"prompts-image-base64-mime",
			"prompts-audio-base64-mime",
			"prompts-embedded-must-include",
			"prompts-resource-link-may",
			"prompts-errors-32602-32603",
			"prompts-validate-args",
			"prompts-validate-io",
			"prompts-respect-capability-negotiation",
		),
		CReq("conformance.TestFeaturesClient",
			"tools-client-exec-errors-to-llm",
			"tools-client-protocol-errors-to-llm-may",
			"tools-name-case-sensitive",
			"tools-resource-link-may-not-listed",
			"tools-x-mcp-header-stdio-may-ignore",
			"resources-client-accept-32002",
			"resources-subscribe-rpc",
			"resources-unsubscribe-follows-subscribe",
			"resources-updated-may-be-subresource",
			"prompts-client-paginate",
			"prompts-respect-capability-negotiation",
		),
	)
	registerGaps(
		Gap{ID: "resources-custom-scheme-rfc3986", Side: Server, Issue: "pending:resource-uri-encoding", Why: "the daemon mints mcpx://<ns>/<upstream uri> by concatenation, without percent-encoding the upstream URI"},
		Gap{ID: "resources-sec-binary-encoded", Side: Server, Issue: "#207", Why: "resources/read only ever answers text: a binary upstream body is described or base64 in the text field, never a blob"},
		Gap{ID: "resources-subscribe-cap-meaning-legacy", Side: Server, Issue: "#208", Why: "subscribe is declared, but the daemon never subscribes upstream, so no update ever arrives to deliver"},
		Gap{ID: "resources-subscribe-cap-meaning-2026", Side: Server, Issue: "#208", Why: "subscribe is declared, but the daemon never subscribes upstream, so no update ever arrives to deliver"},
		Gap{ID: "resources-annotations-defs", Side: Client, Issue: "#207", Why: "mcpclient.Resource has no annotations field; they are dropped on parse"},
		Gap{ID: "tools-display-name-precedence", Side: Client, Issue: "#207", Why: "tool title and annotations.title are carried but nothing that displays a tool uses them"},
		Gap{ID: "tools-annotations-untrusted", Side: Client, Issue: "pending:annotation-trust", Why: "destructiveHint from any upstream decides whether a call is confirmed; an absent or false hint is trusted"},
		Gap{ID: "tools-annotations-hints-no-decisions", Side: Client, Issue: "pending:annotation-trust", Why: "the consumer confirmDestructive gate is decided by an untrusted upstream annotation"},
		Gap{ID: "tools-x-mcp-header-reject-excludes", Side: Client, Issue: "#200", Why: "x-mcp-header is not read, so a tool with an invalid one is not excluded"},
		Gap{ID: "tools-x-mcp-header-reject-log", Side: Client, Issue: "#200", Why: "x-mcp-header is not read, so nothing is rejected or logged"},
		Gap{ID: "resources-subscribe-via-listen", Side: Client, Issue: "#208", Why: "mcpx never opens subscriptions/listen upstream"},
		Gap{ID: "prompts-validate-io", Side: Client, Issue: "pending:prompt-validation", Why: "an upstream prompts/get result is passed on unvalidated"},
	)
}
