package conformance

// Transports: stdio, HTTP+SSE, Streamable HTTP.
func init() {
	register(
		SReq("conformance.TestTransportServer",
			"stdio-no-embedded-newlines",
			"stdio-server-stdout-only-mcp",
			"stdio-server-may-log-to-stderr",
			"stdio-message-is-single",
			"stdio-message-may-be-batch",
			"stdio-server-exit-on-eof",
			"stdio-server-may-close-stdout",
			"stdio-server-stop-cancelled-work",
			"stdio-server-silent-after-cancel",
			"stdio-server-no-requests",
			"stdio-server-cancelled-only-for-listen",
			"streamable-http-server-single-endpoint-post-get",
			"streamable-http-server-single-endpoint-post",
			"streamable-http-server-validate-origin",
			"streamable-http-server-403-invalid-origin",
			"streamable-http-server-bind-localhost",
			"streamable-http-server-202-for-non-request",
			"streamable-http-server-error-status-if-rejected",
			"streamable-http-server-json-or-sse-for-request",
			"streamable-http-sse-includes-response",
			"streamable-http-post-sse-may-carry-requests",
			"streamable-http-sse-not-closed-before-response",
			"streamable-http-server-terminates-sse-after-response",
			"streamable-http-no-broadcast",
			"streamable-http-disconnect-not-cancel",
			"streamable-http-close-is-cancel",
			"streamable-http-stop-cancelled-work",
			"streamable-http-silent-after-cancel",
			"streamable-http-get-sse-or-405",
			"streamable-http-get-close-any-time",
			"streamable-http-server-may-assign-session",
			"streamable-http-session-id-secure",
			"streamable-http-session-id-visible-ascii",
			"streamable-http-server-404-terminated-session",
			"streamable-http-server-may-405-delete",
			"streamable-http-server-may-terminate-on-session-expiry",
			"streamable-http-server-assumes-2025-03-26",
			"streamable-http-server-400-unsupported-version-header",
			"streamable-http-missing-version-header-legacy",
			"streamable-http-header-mismatch-400-jsonrpc",
			"streamable-http-server-rejects-header-body-mismatch",
			"streamable-http-protocol-version-header-matches-meta",
			"streamable-http-server-decodes-before-compare",
			"streamable-http-header-names-case-insensitive",
			"streamable-http-unknown-method-404",
			"streamable-http-unsupported-version-400",
			"streamable-http-missing-capability-400",
			"streamable-http-x-accel-buffering",
			"streamable-http-sse-comment-keepalive",
			"streamable-http-sse-notifications-must-relate",
			"streamable-http-no-resumability",
			"streamable-http-sse-no-requests",
			"http-sse-deprecated-no-new-adoption",
		),
		CReq("conformance.TestTransportClient",
			"transport-client-should-support-stdio",
			"stdio-no-embedded-newlines",
			"stdio-client-stdin-only-mcp",
			"stdio-message-is-single",
			"stdio-client-may-capture-stderr",
			"stdio-client-stderr-not-error",
			"stdio-client-cancel-by-notification",
			"stdio-client-no-responses",
			"stdio-modern-only-client-probe",
			"stdio-no-fallback-on-modern-error",
			"stdio-client-shutdown-sequence",
			"streamable-http-client-post-every-message",
			"streamable-http-client-accept-both",
			"streamable-http-post-body-may-batch",
			"streamable-http-post-body-single",
			"streamable-http-post-body-request-or-notification",
			"http-sse-deprecated-no-new-adoption",
			"streamable-http-no-resumability",
			"streamable-http-client-echoes-session",
			"streamable-http-client-delete-session",
			"streamable-http-client-handles-session-securely",
			"streamable-http-client-supports-json-and-sse",
			"streamable-http-sse-comment-keepalive",
			"streamable-http-client-cancel-by-notification",
			"streamable-http-multiple-streams",
			"streamable-http-protocol-version-header-every-post",
			"streamable-http-protocol-version-header-matches-meta",
			"streamable-http-protocol-version-header-is-negotiated",
			"streamable-http-header-names-case-insensitive",
			"streamable-http-intermediary-http-error",
		),
	)
	registerGaps(
		Gap{ID: "stdio-client-no-responses", Side: Client, Issue: "#200", Why: "a request from a 2026-07-28 server is answered; the client has no era guard on server requests"},
		Gap{ID: "stdio-client-shutdown-sequence", Side: Client, Issue: "#203", Why: "StdioTransport.Close sends SIGTERM as it closes stdin instead of waiting for the child to exit"},
		Gap{ID: "streamable-http-client-cancel-by-notification", Side: Client, Issue: "#203", Why: "over HTTP a timed-out call aborts its own POST and sends no notifications/cancelled; a legacy server keeps working on it"},
		Gap{ID: "streamable-http-protocol-version-header-is-negotiated", Side: Client, Revs: []string{"2025-06-18"}, Issue: "#203", Why: "legacy frames carry MCP-Protocol-Version 2025-11-25 whatever was negotiated"},
		Gap{ID: "stdio-message-may-be-batch", Side: Client, Issue: "#203", Why: "the stdio receive loop drops a line holding a JSON array"},
		Gap{ID: "http-sse-client-backcompat-probe-400-404-405", Side: Client, Issue: "#220", Why: "mcpx has no HTTP+SSE client transport"},
		Gap{ID: "http-sse-client-backcompat-probe-any-4xx", Side: Client, Issue: "#220", Why: "mcpx has no HTTP+SSE client transport"},
		Gap{ID: "http-sse-client-backcompat-probe-non-modern-body", Side: Client, Issue: "#220", Why: "mcpx has no HTTP+SSE client transport"},
		Gap{ID: "http-sse-client-post-to-endpoint", Side: Client, Issue: "#220", Why: "mcpx has no HTTP+SSE client transport"},
		Gap{ID: "streamable-http-client-sends-metadata-headers", Side: Client, Issue: "#200", Why: "the HTTP transport sends no Mcp-Method or Mcp-Name header"},
		Gap{ID: "streamable-http-standard-headers-required", Side: Client, Issue: "#200", Why: "the HTTP transport sends no Mcp-Method or Mcp-Name header"},
		Gap{ID: "streamable-http-mcp-name-base64", Side: Client, Issue: "#200", Why: "the HTTP transport sends no Mcp-Method or Mcp-Name header"},
		Gap{ID: "streamable-http-client-header-construction", Side: Client, Issue: "#200", Why: "the HTTP transport sends no Mcp-Method or Mcp-Name header"},
		Gap{ID: "streamable-http-x-mcp-header-client-must-mirror", Side: Client, Issue: "#200", Why: "x-mcp-header is not read: no Mcp-Param headers, no validation, no relist on -32020"},
		Gap{ID: "streamable-http-client-rejects-invalid-x-mcp-header", Side: Client, Issue: "#200", Why: "x-mcp-header is not read: no Mcp-Param headers, no validation, no relist on -32020"},
		Gap{ID: "streamable-http-param-value-encoding", Side: Client, Issue: "#200", Why: "x-mcp-header is not read: no Mcp-Param headers, no validation, no relist on -32020"},
		Gap{ID: "streamable-http-client-relist-on-header-mismatch", Side: Client, Issue: "#200", Why: "x-mcp-header is not read: no Mcp-Param headers, no validation, no relist on -32020"},
		Gap{ID: "streamable-http-client-polls-after-close", Side: Client, Issue: "#203", Why: "a closed SSE response is not reopened; the pending request waits out its deadline"},
		Gap{ID: "streamable-http-client-respects-retry", Side: Client, Issue: "#203", Why: "the client never reconnects a stream, so retry is never honoured"},
		Gap{ID: "streamable-http-client-reissue-broken-request", Side: Client, Issue: "#203", Why: "a broken response stream is not re-issued with a new id"},
		Gap{ID: "streamable-http-client-resume-with-last-event-id", Side: Client, Issue: "#203", Why: "no Last-Event-ID resumption"},
		Gap{ID: "streamable-http-client-reinit-on-404", Side: Client, Issue: "#203", Why: "a 404 for the session is returned as an error; no new initialize"},
		Gap{ID: "stdio-client-restart-crashed-server", Side: Client, Issue: "pending:stdio-restart", Why: "unverified: the in-flight call fails and the pool respawns only on the next acquire, subject to its start-failure cooldown"},
	)
}
